version: '3.4'

services:

  pdfdb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "123!ErblinH"
      MSSQL_PID: "Express"
    ports:
      - "1435:1433"
    container_name: pdfdb

  pdfapp:
    image: erblinh/pdfapi
    container_name: app
    environment:
      ASPNETCORE_URLS: "http://+:80"
    ports:
      - "80:80"
    depends_on:
      - pdfdb

